### ISSUE TITLE
Comprobación de versión PHP

### ISSUE THREAD

**Issue by rbustos** [TransbankDevelopers/transbank-plugin-prestashop-webpay#26]
Al parecer el servicio de comprobación está descartando las subversiones de PHP compatibles. Esto es: 

> PHP 7.1 OK
> PHP 7.1**.x** NoOK (test usando PHP Version 7.1.25)
![screenshot from 2018-12-29 18-00-34](https://user-images.githubusercontent.com/263415/50542134-77885700-0b94-11e9-80aa-ea5d53b49e33.png)

En PHP 7.2 confirmé que funciona sin inconveniente pero el módulo indica que no es compatible.

**Comment by eperaltar** [comment]
Estimados, nos ocurre lo mismo.

Queremos implementar sobre Prestashop en versión 7.1.26, subversión compatible con la 7.1 y nos indica lo mismo.

¿Cómo podemos resolverlo? Tuvimos que implementar otros recaudadores para poder operar mientras tanto. Nuestro sitio tiene cerca de 600 compras mensuales.

Saludos

**Comment by rbustos** [comment]
Hola, solo como dato.. aún cuando indica que no es compatible.. no tiene problemas para funcionar. Esto al menos en mis pruebas.

Si requiere un fix para la comprobación y/o aceptar las versiones nuevas de php.

**Comment by Leous88** [comment]
es solo un tag informativo.... se arregla muy facil. puedes operar tranquilamente. 

> Estimados, nos ocurre lo mismo.
> 
> Queremos implementar sobre Prestashop en versión 7.1.26, subversión compatible con la 7.1 y nos indica lo mismo.
> 
> ¿Cómo podemos resolverlo? Tuvimos que implementar otros recaudadores para poder operar mientras tanto. Nuestro sitio tiene cerca de 600 compras mensuales.
> 
> Saludos

**Comment by a1b4** [comment]
Hola a todos, como mencionas esto es simplemente una validación. Las pruebas realizadas han validado el correcto funcionamiento hasta la versión 7.1.24.
Alguno de ustedes ha tenido problemas de funcionamiento con las versiones 7.1.25 o 7.1.26?

Saludos.

**Comment by Leous88** [comment]
todo funciona ok. incluso implemente, por mi parte php 7 cuando se suponia el modulo era compatible hasta la version 5.6 ! . ya en el foro de transbankdevelopers lo mencioné. Saludos.

**Comment by a1b4** [comment]
Hola, la[ última versión del plugin](https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay/releases/latest) es compatible con php 7.2 y prestashop 1.7.5.2
