### ISSUE TITLE
peticion

### ISSUE THREAD

**Issue by Leous88** [TransbankDevelopers/transbank-plugin-prestashop-webpay#30]
quisera saber si es factible , ( cre oque si ) que por favor el voucher o la informacion de arroja el voucher en la pagina de confirmacion de pedidos tambien sea añadida al backoffice de prestashop. 

por lo menos los datos de : 
Número de la tarjeta  (los ultimos 4 digitos)
Marca de la tarjeta (debito o credito)
Id transaccion.
Gracias.
![captura de pantalla 2019-02-08 18 28 59](https://user-images.githubusercontent.com/44386425/52507375-1c547600-2bd0-11e9-8aae-5e86e6cf07f7.png)

**Comment by a1b4** [comment]
@Leous88 Hola, muchas gracias por el mensaje y solicitud de cambio, lo consideraremos como una posible mejora.

Por otro lado, este repositorio es open source por lo que puedes realizar el cambio (si lo deseas) y aportar con un Pull Request. :)

Saludos.

**Comment by Leous88** [comment]
Hola, gracias por lo visto el modulo webpay ya incluye alguna info en el apartado mencionado. lo agregaron en una version posterior al post. Gracias nuevamente.
