### ISSUE TITLE
Pedidos no siempre se reflejan como pagados

### ISSUE THREAD

**Issue by pparga** [TransbankDevelopers/transbank-plugin-prestashop-webpay#34]
En algunos pedidos, después de que son correctamente pagados, estos no aparecen como pagados en el backoffice si no que como cancelados.  

Este error ocurre en pocos casos pero generan un gran problema ya que hay que comprobar a través de transbank que el pedido efectivamente fue pagado.

**Comment by a1b4** [comment]
@pparga Hola, el problema aún persiste, encontraste algún patrón? los pedidos aparecen como pagados y después cambian a cancelados  o pasan a cancelados directamente?

**Comment by pparga** [comment]
Hola, el problema aun persiste. Eso sí, el problema ahora es que en vez de aparecer como cancelado el pedido, este no aparece en el BackOffice de Prestashop pero sí aparece la transacción en Transbank.

Lo único que he encontrado en los logs es un Fatal error del smarty Cache:
_Got error 'PHP message: PHP Fatal error:  Uncaught  --> Smarty: Missing template name <-- \n  thrown in /opt/sdp/o2sportsoutlet/vendor/prestashop/smarty/sysplugins/smarty_internal_template.php on line 678\n', referer: https://webpay3g.transbank.cl/webpayserver/auth_emisor.cgi_

**Comment by a1b4** [comment]
@pparga hola, hay alguna opción de saber en que parte del plugin obtienes el error. Por lo que veo puede ser que te falte algun template, pero como hay varios me sería más fácil hacer las pruebas sabiendo cual de todos es el que te está dando problemas.

**Comment by Leous88** [comment]
esto ocurre, a veces pero es problema directo de la tienda prestashop. debes reinicializar el modulo, luego borrar cache de prestashop. eso siempre soluciona el problema. lo otro es la configuración de los pedidos. allí debes señalar el comportamiento de los pedidos "validados" y "pagados", asi le dices a presta que hacer con cada estado. eso ya lo encontraras resuelto en el foro de prestashop. o si requieres ayuda, con gusto te la brindo.  Por lo cual no es problema ni del modulo ni de transbank. ya lo veras cuando te ocurra la misma situacion con otros módulos tales como facturación y otros. Saludos.

**Comment by pparga** [comment]
Perfecto! Muchas gracias @Leous88, probare lo que dices.

**Comment by a1b4** [comment]
@pparga Buen día, como te fue con las pruebas que mencionó @Leous88 ? podrías contarnos si has podido solucionar el tema?
Saludos

**Comment by a1b4** [comment]
@pparga ya que no hemos obtenido respuesta cerraremos este issue, por favor informarnos su el problema aun persiste, para re-abrirlo.
