### ISSUE TITLE
Estado del pedido en preparación

### ISSUE THREAD

**Issue by FranciscoArenas** [TransbankDevelopers/transbank-plugin-prestashop-webpay#43]
El estado del pedio queda en "PS_OS_PREPARATION" pero no pasa por la confirmacion del pago 

"PS_OS_PAYMENT"

como lo hacen los demas addons de pago como (onepay, paypal, entre otros)

lo que produce que las validaciones de descarga de productos digitales o envio de respuestas no se ejecuten.

Estados del pedidos : no gatilla el hook Action Payment Confirmation

**Comment by a1b4** [comment]
@FranciscoArenas muchas gracias por reportar esto, realizaremos la verificación de lo que mencionas para solucionar lo que sea necesario.

**Comment by ricardo-salas-letelier** [comment]
Al igual que Francisco, quiero que el estado de la orden después de pagar sea "PS_OS_PAYMENT"

¿Habrá ya alguna solución?

**Comment by Trimas** [comment]
Lo solucioné ingresando a
modules/webpay(elnombredetumodulo)/controllers/front/ y editas el archivo validate.php buscas

$OKStatus = Configuration::get('PS_OS_PREPARATION'); y la cambias por

$OKStatus = Configuration::get('PS_OS_PAYMENT');

Ahí al cerrar la venta, el estado de confirmación de tu pedido en tu BO aparece como "pago aceptado" y no "preparación en curso"

**Comment by ricardo-salas-letelier** [comment]
Trimas, la solución aplica bien. Gracias.

De todas maneras, sería bueno que el módulo permitiera definir el estado en que queda la orden después de pagar.

**Comment by gdespirito** [comment]
Hola. Esto se puede hacer pero con el plugin REST. Este plugin SOAP está obsoleto, por lo que cerraré el issue.
