### ISSUE TITLE
This value should not be null

### ISSUE THREAD

**Issue by Kalucyfer** [TransbankDevelopers/transbank-plugin-prestashop-webpay#44]
trato de hacer la instalación normal del plugin según el tutorial...

aparece este mensaje al momento de subir el modulo "this value should not be null"

algún consejo? o algo que me este saltando?

**Comment by a1b4** [comment]
Hola @Kalucyfer según lo reportado por otros usuarios esto se solucionar aumentando el max_upload del php.ini. Podrías por favor probar esto.

Saludos.

**Comment by Kalucyfer** [comment]
gracias!

**Comment by a1b4** [comment]
voy a cerrar este issue, si el problema persiste por favor avisanos para re-abrir.
saludos.

**Comment by Kalucyfer** [comment]
correcto... el problema se soluciono dejando en el upload_max_filesize en
128M
memory_limit en 128M
y porsiacaso el post_max_size en 128M
y se instalo sin ningun problema. todo funcionando! gracias.
