### ISSUE TITLE
Error en query validate.php

### ISSUE THREAD

**Issue by j-arias** [TransbankDevelopers/transbank-plugin-prestashop-webpay#48]
En el controller **WebPayValidateModuleFrontController** (validate.php) en la **linea 51** al armar la query no se está utilizando la constante **\_DB_PREFIX\_** para el prefijo de la tabla, esto provoca errores en el proceso de la compra cuando el prefijo es diferente a **ps_**

**Comment by gdespirito** [comment]
Hola @j-arias. Gracias por darte cuenta. Tienes razón, hay que cambiar eso ¿te gustaría realizar un Pull Request con ese cambio? Así quedarías como autor de ese fix en el repositorio y quedaría arreglado para el próximo release. 😄

**Comment by Alexanderlaiho** [comment]
Estimados, consulta esto nunca se corrigió ??, me di cuenta de esto en un error que me salia, me mandaron el ultimo plugin para prestashop, pero veo que todavía sigue igual en la rama también esta sin modificar. 
Alguien sabe si es la unica linea que llama directo a la tabla sin ocupar la constante _DB_PREFIX_ para el prefijo de la tabla,??

**Comment by ffiebig** [comment]
😱 me carga cuando se nos quedan cosas así atrás, mil disculpas, tenemos que solucionarlo 👷
