### ISSUE TITLE
Eliminar un paso en el proceso de pago Prestashop

### ISSUE THREAD

**Issue by msaustral** [TransbankDevelopers/transbank-plugin-prestashop-webpay#57]
hola al momento de escoger medio de pago Webpay plus en la plataforma: 

![webp1](https://user-images.githubusercontent.com/46203943/81753507-f3312e00-9481-11ea-9114-7afa0e683d15.png)

el modulo nos envía a otra página para confirmar el pago:

![webp2](https://user-images.githubusercontent.com/46203943/81753526-03490d80-9482-11ea-8b5b-faeb58554e8e.png)

este proceso genera fricción con la experiencia del cliente, no conseguí como saltar este paso como tal pero si un work around que le de submit al botón automáticamente:

en el directorio Ps_intalación\modules\webpay\views\templates\front editamos el archivo payment_execution.tpl en la línea 6 agregamos una etiqueta name al form antes de > quedando de esta forma:
`<form method="post" action="{$url}" name="webpay-form">`

Luego en la línea 28 antes del cierre del {/if} insertamos el siguiente JS

```
<script type="text/javascript">
            window.onload = function(){
                document.forms['webpay-form'].submit();
            }
        </script>
    {/if}
```

esto lo que va a hacer es que si existe el token, automáticamente llamara al evento submit del formulario y no solicitara interacción por parte del cliente.

Espero que alguien pueda aportar una mejor solución, saludos.

**Comment by gdespirito** [comment]
Gracias @msaustral, no se p[orque no es hizo así en un comienzo, pero podemos aplciarlo perfectamente. En el resto de los plugins me parece que lo tenemos de esa forma. 

Anotado en el backlog.

**Comment by msaustral** [comment]
Nosotros aplicamos esos cambios para piwen.cl y hasta ahora han trabajado sin problemas. 

Con solo agregar el query para crear los campos al instalar el plugin debería bastar para crear los campos.

Luego hay que hacer un cambio en el backoffice para que lo muestre en cada pedido.

También hay un tema que nunca logramos resolver y es que al aprobar el pedido, la plataforma manda el correo de confirmación antes de guardar los datos en la BD y el comprobante que llega al correo del cliente no tiene los datos adicionales.

Si en el backoffice le damos re-enviar correo si salen los datos adicionales, saludos.

**Comment by msaustral** [comment]
perfecto, saludos.

**Comment by gdespirito** [comment]
En [este PR](https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay/pull/71) quedó aplicado. Gracias por la sugerencia.
