### ISSUE TITLE
Pago duplicado

### ISSUE THREAD

**Issue by EddGreen** [TransbankDevelopers/transbank-plugin-prestashop-webpay#58]
Hola, 
en todas las ordenes el monto "pagado" aparece como el doble del real, y esto genera una advertencia en BackOffice para cada orden. Esto es un ejemplo con una orden reciente:
![WebPay Pago duplicado](https://user-images.githubusercontent.com/65938148/83346394-ef0e6880-a2e9-11ea-9636-c96244aa7d44.JPG)

Esto también hace que el total de compra registrado para el cliente se vea incrementado al doble:
![WebPay Pago duplicado_2](https://user-images.githubusercontent.com/65938148/83346412-1d8c4380-a2ea-11ea-9b50-3e147902dd4d.JPG)

El monto real descontado al cliente es el correcto, y a nosotros también nos aparece correctamente reflejado en Transbank, pero los registros en BackOffice se general de forma incorrecta.

Estoy usando Prestashop 1.7.6.5 y la versión 3.1.2 del módulo de WebPay, pero el error viene desde versiones anteriores. Actualmente uso la función de Multi-Store; tengo 2 tiendas creadas y funcionando con el módulo. No sé si el problema tenga que ver con esto, o si se debe a algo más.

De antemano gracias,
Edd.

**Comment by ffiebig** [comment]
Gracias por el reporte @EddGreen vamos a tratar de replicar y solucionar el problema

**Comment by diegoaces** [comment]
Estimados, estoy con la ultima version del plugin tbk en un Prestashop v1.7.5.2 y me da el mismo problema, existirá alguna solución
![image](https://user-images.githubusercontent.com/45692265/85314285-46d26680-b487-11ea-8c7a-3bc7bc8bc386.png)

**Comment by dvargas2010** [comment]
Estimados, alguien le ha podido dar solución al error antes mencionado, desde mediados de Julio eh comenzado a tener el mismo problema con el módulo.

**Comment by gdespirito** [comment]
Hola! Aún tienes el mismo problema?

**Comment by ivanp26** [comment]
Asi es, sigue ocurriendo el problema
