### ISSUE TITLE
TimeOut en acknowledgeTransaction

### ISSUE THREAD

**Issue by fblume28** [TransbankDevelopers/transbank-plugin-prestashop-webpay#59]
Tenemos un problema con transacciones por cuales parece que el módulo no responde dentro de los 30 segundos al acknowledgeTransaction. Creemos que el problema viene de un gran volumen de transacción.

Quería saber si haya algunas recomendaciones para optimizar el tratamiento en el servidor : eliminación de datos, creación de index,...

En los logs, no hay nada relevante. Tenemos muchos error de tipo :  Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart.

**Comment by ffiebig** [comment]
Hola @fblume28 tienes por ahí el error ? Me gustaría verlo completo, vamos a echarle una mirada a lo que reportas. Igual han pasado 8 días, sigues con el problema ?

**Comment by fblume28** [comment]
Hola Felipe,

Sí, el problema continua. Estamos en contacto también con el soporte web de
Transbank.

Te pongo el ejemplo de un carrito por el cual tengo el detalle que me
mandaron :
![Detaille transaccion reversada](https://user-images.githubusercontent.com/62021104/84429316-ec6b1780-abf5-11ea-9313-901fa72848fd.png)


No hay nada en los logs.

Lo que sabemos :
- El caso ocurre sobre más de 15% de las transacciones en media al día.
Parece que haya más cuando hay más transacciones :
![Transacciones per hora](https://user-images.githubusercontent.com/62021104/84429294-e2491900-abf5-11ea-8c91-6dc210ed5614.png)


- No se genera el pedido por parte de Decashop pero aparece con el
estado reversada la transacción en el sitio de Transbank.
[image: Capture d’écran 2020-06-11 à 11.24.30.png]
- No tenemos informaciones sobre el OS/Web browser de nuestros clientes
para ver si hay algo relacionado. Lo vamos a activar dentro de algunos días
para verlo.

Necesitas algunas informaciones precisas ?
Como podemos ir adelante para analizar lo que está pasando ?


Le jeu. 11 juin 2020 à 10:49, Felipe Fiebig <notifications@github.com> a
écrit :

**Comment by ffiebig** [comment]
@fblume28 al parecer la foto que enviaste no llegó a github, me interesa verla.

Por el momento no necesito más info, cuando me meta de lleno a solucionarlo probablemente te contacte para más info. Por lo que veo es algo que tomaremos pronto

**Comment by fblume28** [comment]
Te mando los screenshots como archivos adjuntos.
n
[image: Decathlon]
*#Solution&Technology*



*  Franck BLUMENFELD*

  IT Country Leader

  Decathlon Chile
  +56 9 3914 9058


Le jeu. 11 juin 2020 à 11:49, Felipe Fiebig <notifications@github.com> a
écrit :

**Comment by ffiebig** [comment]
@fblume28 los adjuntos que pones en el correo no llegan a Github, no puedo ver las fotos. Puedes subirlas directo al issue en Github ?

**Comment by fblume28** [comment]
![Detaille transaccion reversada](https://user-images.githubusercontent.com/62021104/84429153-b332a780-abf5-11ea-8913-7e0f6d958453.png)
![Transacciones per hora](https://user-images.githubusercontent.com/62021104/84429191-be85d300-abf5-11ea-868b-bc071bedb617.png)

**Comment by ffiebig** [comment]
Gracias !

**Comment by fblume28** [comment]
Adicional info : parece que el problema viene de la configuración SameSite=Lax.
Con algunos navegadores se bloquea si no está None y Secured.
<img width="1177" alt="Capture d’écran 2020-06-17 à 18 18 56" src="https://user-images.githubusercontent.com/62021104/84957980-5c800e80-b0ca-11ea-90a1-db29f50e01c8.png">

**Comment by ffiebig** [comment]
Gracias por la info @fblume28

**Comment by gdespirito** [comment]
Puede que tenga que ver con la actualización de Chrome en la versión 80, para el bloqueo de las cookies. Lo que hemos hecho en otros plugins es dejar de usar variables de sesión.

**Comment by fblume28** [comment]
Creo que sería lo mejor. En una nueva versión del plugin ? Cuál sería el tiempo necesario para hacer el cambio ?

**Comment by gdespirito** [comment]
@fblume28 Como el equipo maneja más de 20 plugins oficiales, habría que agregarlo a la lista de pendientes para tratar de darle prioridad, pero no podemos establecer ni comprometer fechas tentativas para que el equipo lo tome. 
De todas formas, como son todos proyectos opensource, si logran resolverlo internamente, pueden hacer un PR a este repositorio. 

Primeramente necesitamos poder replicar el error, por lo que habría que hacer las pruebas con una nueva instalación de prestashop y ver si falla. ¿tienen algun patrón que nos permita replicar el error?

**Comment by ivaldes2786** [comment]
Experimento el mismo problema en mi tienda. Hay alguna actualización en camino?

**Comment by msaustral** [comment]
hola buenas tardes, tenemos falla con un cliente ya se agrego la linea 

`<script type="text/javascript">
     document.cookie = 'SameSite=None; Secure';
     window.onload = function(){
        document.forms['webpay-form'].submit();
      }
</script>
`

en modules/webpay/views/templates/front/payment_execution.tpl
pero el cliente sigue teniendo muchas transacciones reversadas

alguna idea??

**Comment by ffiebig** [comment]
Hola @msaustral hemos ido viendo posible soluciones a esto pero la verdad el problema de raíz está en Prestashop y el servidor web a través del cual se sirve. Tenemos que hacer un par de pruebas más aún para recomendar algo, pero, sería un workaround y no una solución definitiva ya que se escapa completamente de lo que se puede hacer a través del código de este Plugin.

De todas maneras te recomiendo que revises Prestashop mismo usuarios han reportado que han tenido que hacer modificaciones ahí para hacerlo funcionar

**Comment by msaustral** [comment]
> Hola @msaustral hemos ido viendo posible soluciones a esto pero la verdad el problema de raíz está en Prestashop y el servidor web a través del cual se sirve. Tenemos que hacer un par de pruebas más aún para recomendar algo, pero, sería un workaround y no una solución definitiva ya que se escapa completamente de lo que se puede hacer a través del código de este Plugin.
> 
> De todas maneras te recomiendo que revises Prestashop mismo usuarios han reportado que han tenido que hacer modificaciones ahí para hacerlo funcionar

Hola buen día, ya conseguimos la solución definitiva, hay que hacer un cambio en el core de Prestashop, saludos.

**Comment by dreamgonz** [comment]
Hola @msaustral podrias compartir la solución definitiva??? llevamos varios dias tratando de solucionar sin exito. Agradezco tu ayuda. Saludos

**Comment by msaustral** [comment]
Hola, hay que hacer una modificación en el núcleo de Prestashop y requiere unas horas técnicas, saludos.

**Comment by erwin254** [comment]
@msaustral manda el pedazo de codigo mejor xD

**Comment by carlysjgg** [comment]
Hola. Alguien ha podido dar con la solución y pueda compartir que debe hacerse?

**Comment by msaustral** [comment]
> Hola. Alguien ha podido dar con la solución y pueda compartir que debe hacerse?

https://github.com/msaustral/Prestashop-cookies
