### ISSUE TITLE
Luego de realizar pago, no se actualiza el estado de la orden.

### ISSUE THREAD

**Issue by juanr-yes** [TransbankDevelopers/transbank-plugin-prestashop-webpay#62]
Hola, buen día. Espero se encuentren bien.

No se si es que no está contemplado dentro del funcionamiento del plugin, pero luego de realizar el pago de una orden y que esta sea exitosa, no se actualiza automáticamente el estatus de la orden. Agradecería su respuesta de cara a esta situación.

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 3.1.0
- Prestashop: 1.6.1.17
- PHP: 7.0.33

Quedo atento, muchas gracias por el plugin! 
Que estén bien.

**Comment by ricardo-dota** [comment]
A mi me ocurre lo mismo , pero solo en celulares, he dejado el issue después de este  https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay/issues/64
