### ISSUE TITLE
Error TCPDF al retornar luego del pago

### ISSUE THREAD

**Issue by rquirola** [TransbankDevelopers/transbank-plugin-prestashop-webpay#67]
Estimados,
Estoy usando prestashop 1.6 con PHP 5.4

Cuando la transacción retorna del pago aparece un error en la ruta /module/webpay/validate
El mensaje se puede ver en esta imagen: https://ibb.co/dJfvgm1

El mensaje ocurre en 4 de cada 6 pagos.
Se utiliza el plugin Prestashop versión 3.1.2

Espero puedan solucionarlo, saludos.

**Comment by afiebig** [comment]
Hola Rquirola, puedes descartar que no sea una imagen que no se encuentra en tu ecommerce? al parecer tcpdf trata de encontrar la imagen de algún producto y no la consigue. Puedes verificar por favor si esas 4 de cada 6 pagos estan relacionados a un mismo item por ejemplo?

**Comment by gdespirito** [comment]
Hola @rquirola ¿Este bug sigue activo o era otro problema?

**Comment by rquirola** [comment]
Hola estimados, el problema fue otra consecuencia del cierre de sesiones de prestashop ocasionado por el manejo de las cookies, tras solucionar el tema de las sesiones el problema no apareció más. Saludos.

**Comment by gdespirito** [comment]
Gracias por comentar!
