### ISSUE TITLE
Cookies Browser

### ISSUE THREAD

**Issue by nicolasriquelme62** [TransbankDevelopers/transbank-plugin-prestashop-webpay#69]
When can browser cookies resolve?

[Comunicado Plugin Webpay Transbank.pdf](https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay/files/5199064/Comunicado.Plugin.Webpay.Transbank.pdf)

**Comment by erwin254** [comment]
estoy en las mismas, no sabía que era tan masivo el problema, esperemos que lo solucionen luego xD
