### ISSUE TITLE
No se carga el estado de la orden luego de pagar en ambiente productivo

### ISSUE THREAD

**Issue by Danianez** [TransbankDevelopers/transbank-plugin-prestashop-webpay#76]
Tengo instalación de Prestashop 1.7.6.8 y estoy presentando problemas con el modulo Transbank, cuando realizo las pruebas de integración funciona correctamente el modulo y me devuelve a la pagina web de resumen del pedido finalizando correctamente la compra de pruebas.

Pero cuando cambio las credenciales productivas y realizo una compra de pruebas por cualquier valor, luego de ingresar mis datos de tarjetas reales y procesar el pago, al momento de volver a la pagina de resumen me entrega un error 500 la pagina web y cuando lo coloco en modo depuración para revisar el error me indica lo siguiente:

[PrestaShopException]
Can't load Order status
at line 243 in file classes/PaymentModule.php

Adjunto archivo ampliado de este error.

[validate.pdf](https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay/files/5398009/validate.pdf)

Luego de este error, y revisar los carros en mi pagina este pedido queda como carrito abandonado.
Cuando devuelvo el modulo a pruebas de integración me funciona el pago de pruebas.

Realizo los test de comunicación del ambiente productivo y todos los test pasan sin problemas. 

Cabe destacar que el modulo estaba operando sin problemas y de un momento a otro comencé a tener estos problemas en la web.

Versiones de sistemas: 
Prestashop 1.7.6.8
Webpay: 3.2.0
PHP: 7.1.33

Espero puedan ayudarme con este problema.

Saludos a toda la comunidad.

**Comment by carlysjgg** [comment]
Hola @Danianez esto comenzó luego de actualizar la versión de Webpay?

**Comment by Danianez** [comment]
Si, tuve que contratar un desarrollador para revisar el tema y me corrigió el problema, segun me comentó el modulo estaba enviando un valor 0 en el cambio de estado y obviamente ese estado 0 no existia en la pagina web por lo que la pagina web rechazaba el pedido. Si bien por el lado de webpay se aprobaba la transacción en producción  al momento de responderle a la pagina la pagina lo rechazaba porque no tenia ese estado cero.

Por ahora ya quedó resuelto.

Saludos y gracias.

**Comment by carlysjgg** [comment]
Hola @Danianez. Sabes si lo resolvió a nivel de prestashop o a nivel del módulo webpay?

**Comment by Danianez** [comment]
Las modificaciones fueron del lado de prestashop, en la base de datos no se guardo bien el estado que enviaba webpay y por eso rechazaba el pedido.

**Comment by mergan77** [comment]
estimado tengo exactamente el mismo problema, podría indicar por favor  como soluci0narlo
