### ISSUE TITLE
Issues en temas 1.7

### ISSUE THREAD

**Issue by rbustos** [TransbankDevelopers/transbank-plugin-prestashop-webpay#9]
Hola! primero gracias por este módulo y el trabajo en él.

Les comento que por algún motivo ciertos themes nuevos tienen problemas al usar el módulo de webpay (versión 3.0.7 y 3.0.8) particularmente cuando acceden al archivo "/webpay/views/templates/front/**payment_execution.tpl**"

Especialmente aquí:

```
{if isset($tpl_dir)}
    {include file="$tpl_dir./order-steps.tpl"}
    {include file="$tpl_dir./errors.tpl"}
{/if}
```

Parece ser que PS1.7 o bien algunos temas tienen problemas al intentan ubicar estos archivos indicados ahí cuando son convertidos por smarty.

El error es el siguiente:

> [26-Nov-2018 01:21:35 America/Santiago] PHP Fatal error:  Uncaught  --> Smarty: Unable to load template 'file:/home/sitio_test/public_html/themes/at_decor/./order-steps.tpl' in 'module:webpay/views/templates/front/payment_execution.tpl' <-- 

Como workaround y solo como test.. al eliminar esas filas el proceso de pago no tuvo inconvenientes.

El log completo es el siquiente:

>  (1/1) SmartyException
> 
> Unable to load template 'file:/home/sitio_test/public_html/themes/at_oreo/./order-steps.tpl' in 'module:webpay/views/templates/front/payment_execution.tpl'
> in smarty_internal_template.php line 187
> at Smarty_Internal_Template->render()in smarty_internal_template.php line 365
> at Smarty_Internal_Template->_subTemplateRender('/home/sitio_test/public_html/themes/at_oreo/./order-steps.tpl', null, 'layouts/layout-full-width.tpl', 0, 3600, array(), 0, true)in bfef76c77571de1a6cd2e9e4801e1472f4ee8b54_2.module.webpayviewstemplatesfront.php line 30
> at content_5bfec9b8b861c4_07375886(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
> at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
> at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
> at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
> at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'layouts/layout-full-width.tpl', null, 0)in smarty_internal_templatebase.php line 116
> at Smarty_Internal_TemplateBase->fetch('module:webpay/views/templates/front/payment_execution.tpl', null, 'layouts/layout-full-width.tpl', null, false, true, false)in SmartyDev.php line 41
> at SmartyDev->fetch('module:webpay/views/templates/front/payment_execution.tpl', null, 'layouts/layout-full-width.tpl')in FrontController.php line 679
> at FrontControllerCore->smartyOutputContent('module:webpay/views/templates/front/payment_execution.tpl')in FrontController.php line 663
> at FrontControllerCore->display()in Controller.php line 275
> at ControllerCore->run()in Dispatcher.php line 428
> at DispatcherCore->dispatch()in index.php line 28

**Como reproducirlo:** 

Generar una compra (PS 1.7.4.2) y seleccionar webpay.. al momento que se hace click sobre el botón y activa el módulo se despliega el error indicado.

**Comment by vutreras** [comment]
@rbustos Hola, gracias por el aviso, fue corregido en el release 3.0.10.
